name: dsci-532-m1

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pip
  - pandas
  - plotly
  - jupyterlab
  - ipykernel
  - pip:
      - dash
      - dash-bootstrap-components